# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 网易新闻

pod 'SDWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYModel'
pod 'FMDB'

  target '网易新闻Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
